### ISSUE TITLE
[iOS-111] Add A Splash Screen

### ISSUE THREAD

**Issue by thesoupgirl** [P2PLisa/CourseRater#14]
As a new iOS user, it would be nice to have a screen to see while the login page will be loading.  This way, it is clear which app I have just opened, and it would be nice if this was pleasant to look at.

ID #:  111
Reference:  http://www.appcoda.com/how-to-add-splash-screen-in-your-ios-app/

Acceptance Criteria:
-Created a new branch
-Have a splash screen
-Image just needs to be the right size.  For now, this can be a filler/default/whatever image, but if you'd like, you can do more work to make this image actually look half decent
-Have this screen be the first thing you see when the app is launched

**Comment by kjy1997** [comment]
Hey I did the splash screen! Not sure what style we are doing but just an idea

**Comment by thesoupgirl** [comment]
Okay yeah, it's just a placeholder for now :)  when we meet up this week, I'll start talking about design.  Since you're done, would you mind creating a pull request and assigning me as the reviewer?

**Comment by kjy1997** [comment]
I created a branch called SplashScreenAngel. How do I create a pull request?

**Comment by thesoupgirl** [comment]
If you go to the IOSCourseRater repo on github, then click 'branches' in the top menu, you'll see all the active branches.  Next to the SplashScreenAngel branch, you should see 'New Pull Request'.  Click that.  After you click that, it should take you to a screen called 'Open a pull request'.  Make sure you assign me to it, by going over to the right hand side of your screen.  You should see 'labels', 'Milestone', and finally underneath that, 'Assignee'.  Click the gear next to 'Assignee'.  Click 'Create Pull Request' to officially create it.
