### ISSUE TITLE
iOS Dev Language

### ISSUE THREAD

**Issue by thesoupgirl** [P2PLisa/CourseRater#2]
As an iOS developer, I would like to know which language we are going to be using to program the iOS version of the app.

Acceptance Criteria:
-Comment below picking either Swift or Obj-C

**Comment by abhic001** [comment]
Swift

**Comment by kjy1997** [comment]
Swift

**Comment by zhuoyachen526** [comment]
Swift

**Comment by thesoupgirl** [comment]
Guess we are going to use Swift!  Awesome!
