### ISSUE TITLE
Git Tutorial

### ISSUE THREAD

**Issue by thesoupgirl** [P2PLisa/CourseRater#4]
All of you need to do a tutorial on Git.  We will be using version control the whole time.
Here's the link:  https://try.github.io/

Acceptance Criteria:
-Have completed the entire tutorial
-Commented below saying that it has been completed

**Comment by thesoupgirl** [comment]
I did this long ago. Very useful! :+1:

**Comment by kjy1997** [comment]
Done it!

**Comment by thesoupgirl** [comment]
Yay! :)  Enjoy the iOS tutorial!  Make sure you have Xcode version 6 or 7 before starting...I'm about to push my Swift repo...

**Comment by abhic001** [comment]
Hey thanks for sending this. I was working to get my VPN running so finally I can access gmail. I will try to do this by today :)

Best,
Abhijeet Chakrabarti
Freshman
Purdue University

**Comment by zhuoyachen526** [comment]
Done :)

**Comment by rkashuka** [comment]
Done :100:
