### ISSUE TITLE
Backend Dev Language

### ISSUE THREAD

**Issue by thesoupgirl** [P2PLisa/CourseRater#5]
As a team, we need to make sure that our backend is easily integrated into all our front-end platforms.

Acceptance Criteria:
-Backend language MUST be easily integrated into each front-end platform (web, iOS, and Android)
-Backend language MUST be approved by Lisa
-All suggestions should be posted below.

**Comment by kjy1997** [comment]
Java

**Comment by rkashuka** [comment]
Java

**Comment by thesoupgirl** [comment]
So it'll be Java!
